

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `questoesapp`
--
USE questoesapp;
-- --------------------------------------------------------

--
-- Table structure for table `QUESTAO`


CREATE TABLE `QUESTAO` (
  `ID` int(11) NOT NULL,
  `PERGUNTA` varchar(255) NOT NULL,
  `ALTERNATIVAA` varchar(255) NOT NULL,
  `ALTERNATIVAB` varchar(255) NOT NULL,
  `ALTERNATIVAC` varchar(255) NOT NULL,
  `ALTERNATIVAD` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



--
-- Indexes for table `QUESTAO` as PK
--
ALTER TABLE `QUESTAO`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for table `QUESTAO`
--
ALTER TABLE `QUESTAO`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;